name: Docker Publish

on:
  push:
  schedule:
    - cron: '* * 1,15 * *'  


jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - java_ver: "1.8.0"
            tag: "8"
          - java_ver: "11"
            tag: "11"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Get date
        id: date
        run: echo "::set-output name=today::$(date +'%y%m%d')"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            JAVA_VER=${{ matrix.java_ver }}
          tags: |
            zcx2001/myjdk:${{ matrix.tag }}-${{ steps.date.outputs.today }}
            zcx2001/myjdk:${{ matrix.tag }}-latest