name: Docker Publish

on:
  push:
    paths-ignore:
      - '.github/**'
  schedule:
    - cron: '1 1 1 * *'  

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - java_ver: "1.8.0"
            tag: "8"
          - java_ver: "11"
            tag: "11"
          - java_ver: "17"
            tag: "17"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Get date
        id: date
        run: echo "today=$(date +'%y%m%d')" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            JAVA_VER=${{ matrix.java_ver }}
            RUNNER=github
          tags: |
            zcx2001/myjdk:${{ matrix.tag }}-${{ steps.date.outputs.today }}
            zcx2001/myjdk:${{ matrix.tag }}-latest