name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - java_ver: "1.8.0"
            tag: "8"
          - java_ver: "11"
            tag: "11"
    steps:
      - run: echo "${{ matrix.java_ver }} - ${{ matrix.tag }}"  
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          build-args: |
            JAVA_VER=${{ matrix.java_ver }}
          tags: |
            zcx2001/myjdk:${{ matrix.tag }}